<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Forum - Medical Q&A</title>
  <link rel="stylesheet" href="css/main.css">
  <link rel="stylesheet" href="css/components.css">
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet" />
  <link rel="icon" href="favicon.svg" type="image/svg+xml" />
</head>

<body>
  <!-- Navigation Header -->
  <?php include '../app/partials/navbar.php'; ?>

  <?php
    // Load recent questions and AI answers
    require_once __DIR__ . '/../../config/db.php';
    $pdo = Database::getConnection();
    try {
        $qstmt = $pdo->prepare("SELECT q.id, q.title, q.body, q.ai_answer, q.ai_approved, q.ai_generated, q.created_at, u.username FROM questions q LEFT JOIN users u ON q.user_id = u.id ORDER BY q.created_at DESC LIMIT 20");
        $qstmt->execute();
        $questions = $qstmt->fetchAll(PDO::FETCH_ASSOC);
    } catch (Exception $e) {
        $questions = [];
    }
  ?>

  <!-- Main Content -->
  <main class="main-content">
    <div class="container">
      <div class="forum-header">
        <div class="forum-title">
          <h1>Community Forum</h1>
          <p>
            Connect with others, share experiences, and get support from the
            medical community
          </p>
        </div>
        <div class="forum-actions">
          <button class="btn btn-primary" onclick="startNewDiscussion()">
            <i class="fas fa-plus"></i>
            Start Discussion
          </button>
        </div>
      </div>

      <div class="forum-content">
        <div class="forum-sidebar">
          <div class="filter-card">
            <h3>Filter Discussions</h3>
            <div class="filter-group">
              <label class="filter-label">Category</label>
              <select class="filter-select" id="categoryFilter">
                <option value="">All Categories</option>
                <option value="general">General Discussion</option>
                <option value="symptoms">Symptoms & Conditions</option>
                <option value="treatments">Treatments & Medications</option>
                <option value="lifestyle">Lifestyle & Wellness</option>
                <option value="support">Support & Experiences</option>
              </select>
            </div>
            <div class="filter-group">
              <label class="filter-label">Sort By</label>
              <select class="filter-select" id="sortFilter">
                <option value="recent">Most Recent</option>
                <option value="popular">Most Popular</option>
                <option value="replies">Most Replies</option>
              </select>
            </div>
          </div>

          <div class="stats-card">
            <h3>Forum Statistics</h3>
            <div class="stat-item">
              <span class="stat-number">156</span>
              <span class="stat-label">Active Discussions</span>
            </div>
            <div class="stat-item">
              <span class="stat-number">2,847</span>
              <span class="stat-label">Total Posts</span>
            </div>
            <div class="stat-item">
              <span class="stat-number">1,234</span>
              <span class="stat-label">Community Members</span>
            </div>
          </div>
        </div>

        <div class="forum-main">
          <div class="discussions-list">
            <?php if (empty($questions)): ?>
              <div class="loading-placeholder"><p>No discussions yet.</p></div>
            <?php else: ?>
              <?php foreach ($questions as $q): ?>
                <div class="discussion-item">
                  <div class="discussion-avatar">
                    <img src="https://via.placeholder.com/50/2563eb/ffffff?text=U" alt="User Avatar" />
                  </div>
                  <div class="discussion-content">
                    <div class="discussion-header">
                      <h3 class="discussion-title">
                        <a href="/Medical_Q-A_MIU/public/forum?question_id=<?= intval($q['id']) ?>"><?= htmlspecialchars($q['title']) ?></a>
                      </h3>
                    </div>
                    <p class="discussion-preview">
                      <?= nl2br(htmlspecialchars(substr($q['body'], 0, 300))) ?>
                    </p>

                    <?php if (!empty($q['ai_answer'])): ?>
                      <div class="ai-answer-box">
                        <div class="ai-badge">
                          <span class="badge badge-info">Generated by AI</span>
                          <?php if (intval($q['ai_approved']) === 1): ?>
                            <span class="badge badge-success">Approved by Dr</span>
                          <?php else: ?>
                            <span class="badge badge-warning">Pending doctor approval</span>
                          <?php endif; ?>
                        </div>
                        <div class="ai-answer-preview">
                          <?= nl2br(htmlspecialchars(substr($q['ai_answer'], 0, 400))) ?>
                        </div>
                      </div>
                    <?php endif; ?>

                    <div class="discussion-meta">
                      <span class="discussion-author">by <?= htmlspecialchars($q['username'] ?? $q['username'] ?? 'Anonymous') ?></span>
                      <span class="discussion-time"><?= htmlspecialchars($q['created_at']) ?></span>
                    </div>
                  </div>
                </div>
              <?php endforeach; ?>
            <?php endif; ?>
          </div>

          <div class="pagination">
            <button class="btn btn-outline" disabled>
              <i class="fas fa-chevron-left"></i>
              Previous
            </button>
            <div class="pagination-pages">
              <button class="pagination-page active">1</button>
              <button class="pagination-page">2</button>
              <button class="pagination-page">3</button>
              <span class="pagination-dots">...</span>
              <button class="pagination-page">10</button>
            </div>
            <button class="btn btn-outline">
              Next
              <i class="fas fa-chevron-right"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
  </main>

  <!-- Footer -->
  <?php include '../app/partials/footer.php'; ?>

  <!-- Scripts -->
  <script src="js/main.js"></script>
  <script src="<script src=" js/main.js"></script>/js/controllers/forumController.js"></script>
  <script>
    function startNewDiscussion() {
      if (!MediQA.isLoggedIn) {
        MediQA.showNotification(
          "Please log in to start a discussion",
          "warning"
        );
        setTimeout(() => {
          window.location.href = "login.html";
        }, 1500);
        return;
      }
      // In a real app, this would open a new discussion form or redirect to a new discussion page
      MediQA.showNotification(
        "New discussion feature would be implemented here",
        "info"
      );
    }
  </script>
</body>

</html>